name: Spets Task
description: Start a Spets workflow
labels: ["spets"]
body:
  - type: input
    id: branch
    attributes:
      label: Branch Name
      description: Name for the feature branch
      placeholder: "feature/my-feature"
    validations:
      required: true
  - type: textarea
    id: requirements
    attributes:
      label: Requirements
      description: What do you want to accomplish? (supports multi-line)
      placeholder: |
        Add user authentication
        - Support email/password login
        - Add JWT tokens
    validations:
      required: true
